### ISSUE TITLE
Broken in Silverstripe 4.11

### ISSUE THREAD

**Issue by davejtoews** [davejtoews/silverstripe-embedfield#13]
SilverStripe Framework 4.11 upgrades the requirement for Embed/Embed to version 4.x, up from 3.x in previous releases.

This module does not explicitly require Embed/Embed as a dependency, but it appears to be built around version 3.x. If the dependency was listed in the composer.json it would generate a conflict when attempting to upgrade Silverstripe, however since the dependency is not listed, the composer install completes successfully.

Currently, the CMS field appears but errors out when entering/updating a URL to generate embed content.

**Comment by davejtoews** [comment]
I am looking to see if I can write a PR which gets this working at a minimal level again, however if it turns out this requires sweeping changes I may not be able to complete this.

**Comment by ornatipinnis** [comment]
> I am looking to see if I can write a PR which gets this working at a minimal level again, however if it turns out this requires sweeping changes I may not be able to complete this.

We've encountered the same problem on a number of builds. Someone may have to fork the repo to maintain it.

**Comment by davejtoews** [comment]
There's a patch merged to `master` but not added to a release yet. It's not a complete solution but allows minimal functionality. I haven't had the time to dig deeper, but I suspect if someone offers up a good PR it will get merged. This repo is not dead, it just needs a solution to this issue.

**Comment by sinan-evanshunt** [comment]
Thanks to @davejtoews work, I was able to fix the thumbnail URL along with other attributes that were not working.
A pull request has been created https://github.com/nathancox/silverstripe-embedfield/pull/15 hopefully this gets merged to the `master` branch and a new release with all these fixes is issued.

**Comment by davejtoews** [comment]
Fixed by #16
