### ISSUE TITLE
Not on packagist

### ISSUE THREAD

**Issue by rsmclaren** [davejtoews/silverstripe-embedfield#6]
Could you add this to packagist? It doesn't come up when searching for it.

**Comment by ohararyan** [comment]
Not sure why this has been removed from Packagist as it was there and we have a couple of projects using it. If anyone else is searching in the interim for a fix.

```
{
	"require": {
		"nathancox/embedfield": "dev-master"
	},
	"repositories": [{
			"type": "git",
			"url": "https://github.com/nathancox/silverstripe-embedfield.git"
		}
	]
}

```

**Comment by nathancox** [comment]
This is weird, I have no idea why it wouldn't be on Packagist.  I've added it now though.  Thanks for pointing it out!
